In [2]:
!pip install pymongo

Defaulting to user installation because normal site-packages is not writeable
Collecting pymongo
  Downloading pymongo-4.16.0-cp312-cp312-win_amd64.whl.metadata (10.0 kB)
Collecting dnspython<3.0.0,>=2.6.1 (from pymongo)
  Using cached dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Downloading pymongo-4.16.0-cp312-cp312-win_amd64.whl (907 kB)
   ---------------------------------------- 0.0/907.6 kB ? eta -:--:--
   --------------------------------------- 907.6/907.6 kB 10.2 MB/s eta 0:00:00
Using cached dnspython-2.8.0-py3-none-any.whl (331 kB)
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.8.0 pymongo-4.16.0

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: C:\Users\Bao\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [ ]:
import pandas as pd
from pymongo import MongoClient

# 1. Khởi tạo kết nối đến MongoDB Atlas
# Lưu ý: Khi nộp bài hoặc đẩy lên GitHub/Kaggle, bạn nhớ ẩn mật khẩu này đi nhé (dùng biến môi trường hoặc thư viện dotenv)
client = MongoClient('mongodb+srv://<username>:<password>@cluster0.mongodb.net/')
db = client['ecom_data_lab']

# 2. Truy vấn dữ liệu từ collections (Bỏ qua cột _id nội bộ của MongoDB)
cursor_shops = db['dim_shops'].find({}, {'_id': 0})
cursor_products = db['fact_products'].find({}, {'_id': 0})

# 3. Load toàn bộ dữ liệu vào Pandas DataFrame
df_shops = pd.DataFrame(list(cursor_shops))
df_products = pd.DataFrame(list(cursor_products))

# 4. Kiểm tra dữ liệu đã được load thành công
print(f"Kích thước bảng Shops (dim_shops): {df_shops.shape}")
print(f"Kích thước bảng Products (fact_products): {df_products.shape}")

print("\n--- 3 dòng đầu tiên của bảng Shops ---")
display(df_shops.head(3))

print("\n--- 3 dòng đầu tiên của bảng Products ---")
display(df_products.head(3))

Kích thước bảng Shops (dim_shops): (1980, 11)
Kích thước bảng Products (fact_products): (7014, 12)

--- 3 dòng đầu tiên của bảng Shops ---

,shop_url,seller_id,shop_type,followers,seller_rating,main_category,joined_time,on_time_delivery_rate,cancellation_rate,chat_response_rate,shop_name
0,https://www.lazada.vn/shop/oqrz1tvi/?path=prof...,200983952195,Shop Thường,55.0,0.93,Beauty,9 + tháng,0.98,0.00,0.8333,AuraBelle
1,https://www.lazada.vn/shop/laikou-selection/?p...,200548320478,Shop Thường,201.0,0.98,Beauty,2 + năm,1.00,0.00,0.0000,LAIKOU.Selection
2,https://www.lazada.vn/shop/on-moon/?path=profi...,200164386065,Shop Thường,18894.0,0.96,Beauty,5 + năm,0.97,0.03,0.2000,On Moon

--- 3 dòng đầu tiên của bảng Products ---

,product_id,product_name,category,price,discount,sold_count,rating_score,review_count,location,product_url,image_url,seller_id
0,3140194631,🔥100% hàng thật🔥La Roche-Posay Cicaplast Baume...,Chăm Sóc Da,189.140,0.42,156,4.9,28.0,Vietnam,https://www.lazada.vn/products/pdp-i3140194631...,https://img.lazcdn.com/g/p/67ba4e5cd4ccb841708...,200983952195
1,2496648405,Bộ Chăm Sóc Da Hoa Mận LAIKOU Nhật Bản - 5 Sản...,Chăm Sóc Da,56.000,0.23,2800,4.9,1042.0,Vietnam,https://www.lazada.vn/products/pdp-i2496648405...,https://img.lazcdn.com/g/p/36828d8a5434f8c5a65...,200548320478
2,2784492770,Pores serum Thu Nhỏ Lỗ Chân Lông Úc Tinh Chất ...,Chăm Sóc Da,55.656,0.45,339,5.0,100.0,Vietnam,https://www.lazada.vn/products/pdp-i2784492770...,https://img.lazcdn.com/g/p/b75cb8329d690d4a901...,200164386065